In [53]:
import pandas as pd
import numpy as np

In [54]:
#Task 1. Importing All Dependencies
df = pd.read_csv('provider_info.csv')

In [55]:
#1st five rows
df.head()

,Facility ID,Facility Name,Address,City/Town,State,ZIP Code,County/Parish,Telephone Number,Hospital Type,Hospital Ownership,...,Count of READM Measures Better,Count of READM Measures No Different,Count of READM Measures Worse,READM Group Footnote,Pt Exp Group Measure Count,Count of Facility Pt Exp Measures,Pt Exp Group Footnote,TE Group Measure Count,Count of Facility TE Measures,TE Group Footnote
0,10001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,Acute Care Hospitals,Government - Hospital District or Authority,...,0,11,0,NaN,8,8,NaN,12,11,NaN
1,10005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,(256) 593-8310,Acute Care Hospitals,Government - Hospital District or Authority,...,0,8,1,NaN,8,8,NaN,12,12,NaN
2,10006,NORTH ALABAMA MEDICAL CENTER,1701 VETERANS DRIVE,FLORENCE,AL,35630,LAUDERDALE,(256) 768-8400,Acute Care Hospitals,Proprietary,...,0,8,1,NaN,8,8,NaN,12,10,NaN
3,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,(334) 493-3541,Acute Care Hospitals,Voluntary non-profit - Private,...,0,7,0,NaN,8,8,NaN,12,7,NaN
4,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,(334) 335-3374,Acute Care Hospitals,Proprietary,...,0,2,0,NaN,8,Not Available,5.0,12,6,NaN

In [56]:
# last 5 rows
df.tail()

,Facility ID,Facility Name,Address,City/Town,State,ZIP Code,County/Parish,Telephone Number,Hospital Type,Hospital Ownership,...,Count of READM Measures Better,Count of READM Measures No Different,Count of READM Measures Worse,READM Group Footnote,Pt Exp Group Measure Count,Count of Facility Pt Exp Measures,Pt Exp Group Footnote,TE Group Measure Count,Count of Facility TE Measures,TE Group Footnote
5421,670781,ANSON GENERAL HOSPITAL,101 AVENUE J,ANSON,TX,79501,JONES,(325) 823-3231,Rural Emergency Hospital,Government - Hospital District or Authority,...,Not Available,Not Available,Not Available,19.0,Not Available,Not Available,19.0,Not Available,Not Available,19.0
5422,670783,CHI ST LUKES HEALTH MEMORIAL SAN AUGUSTINE,511 HOSPITAL ST,SAN AUGUSTINE,TX,75972,SAN AUGUSTINE,(936) 275-3446,Rural Emergency Hospital,Voluntary non-profit - Private,...,Not Available,Not Available,Not Available,19.0,Not Available,Not Available,19.0,Not Available,Not Available,19.0
5423,671300,GRAHAM REGIONAL MEDICAL CENTER,1301 MONTGOMERY ROAD,GRAHAM,TX,76450,YOUNG,(940) 549-3400,Critical Access Hospitals,Government - Hospital District or Authority,...,0,3,0,NaN,8,Not Available,5.0,12,5,NaN
5424,671301,HEMPHILL COUNTY HOSPITAL,1020 S 4TH ST,CANADIAN,TX,79014,HEMPHILL,(806) 323-6622,Critical Access Hospitals,Government - Hospital District or Authority,...,Not Available,Not Available,Not Available,5.0,8,Not Available,5.0,12,2,NaN
5425,671302,STEPHENS MEMORIAL HOSPITAL,200 SOUTH GENEVA STREET,BRECKENRIDGE,TX,76424,STEPHENS,(254) 559-2241,Critical Access Hospitals,Government - Hospital District or Authority,...,Not Available,Not Available,Not Available,5.0,Not Available,Not Available,5.0,Not Available,Not Available,5.0

In [57]:
df.shape

(5426, 38)

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5426 entries, 0 to 5425
Data columns (total 38 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Facility ID                                       5426 non-null   object
 1   Facility Name                                     5426 non-null   object
 2   Address                                           5426 non-null   object
 3   City/Town                                         5426 non-null   object
 4   State                                             5426 non-null   object
 5   ZIP Code                                          5426 non-null   int64
 6   County/Parish                                     5426 non-null   object
 7   Telephone Number                                  5426 non-null   object
 8   Hospital Type                                     5426 non-null   object
 9   Hospital Ownership                                5426 non-null   object
 10  Emergency Services                                5426 non-null   object
 11  Meets criteria for birthing friendly designation  2265 non-null   object
 12  Hospital overall rating                           5426 non-null   object
 13  Hospital overall rating footnote                  2572 non-null   object
 14  MORT Group Measure Count                          5426 non-null   object
 15  Count of Facility MORT Measures                   5426 non-null   object
 16  Count of MORT Measures Better                     5426 non-null   object
 17  Count of MORT Measures No Different               5426 non-null   object
 18  Count of MORT Measures Worse                      5426 non-null   object
 19  MORT Group Footnote                               1787 non-null   float64
 20  Safety Group Measure Count                        5426 non-null   object
 21  Count of Facility Safety Measures                 5426 non-null   object
 22  Count of Safety Measures Better                   5426 non-null   object
 23  Count of Safety Measures No Different             5426 non-null   object
 24  Count of Safety Measures Worse                    5426 non-null   object
 25  Safety Group Footnote                             2079 non-null   object
 26  READM Group Measure Count                         5426 non-null   object
 27  Count of Facility READM Measures                  5426 non-null   object
 28  Count of READM Measures Better                    5426 non-null   object
 29  Count of READM Measures No Different              5426 non-null   object
 30  Count of READM Measures Worse                     5426 non-null   object
 31  READM Group Footnote                              1160 non-null   float64
 32  Pt Exp Group Measure Count                        5426 non-null   object
 33  Count of Facility Pt Exp Measures                 5426 non-null   object
 34  Pt Exp Group Footnote                             2275 non-null   float64
 35  TE Group Measure Count                            5426 non-null   object
 36  Count of Facility TE Measures                     5426 non-null   object
 37  TE Group Footnote                                 940 non-null    float64
dtypes: float64(4), int64(1), object(33)
memory usage: 1.6+ MB

In [59]:
df.isnull().sum()

Facility ID                                            0
Facility Name                                          0
Address                                                0
City/Town                                              0
State                                                  0
ZIP Code                                               0
County/Parish                                          0
Telephone Number                                       0
Hospital Type                                          0
Hospital Ownership                                     0
Emergency Services                                     0
Meets criteria for birthing friendly designation    3161
Hospital overall rating                                0
Hospital overall rating footnote                    2854
MORT Group Measure Count                               0
Count of Facility MORT Measures                        0
Count of MORT Measures Better                          0
Count of MORT Measures No Different                    0
Count of MORT Measures Worse                           0
MORT Group Footnote                                 3639
Safety Group Measure Count                             0
Count of Facility Safety Measures                      0
Count of Safety Measures Better                        0
Count of Safety Measures No Different                  0
Count of Safety Measures Worse                         0
Safety Group Footnote                               3347
READM Group Measure Count                              0
Count of Facility READM Measures                       0
Count of READM Measures Better                         0
Count of READM Measures No Different                   0
Count of READM Measures Worse                          0
READM Group Footnote                                4266
Pt Exp Group Measure Count                             0
Count of Facility Pt Exp Measures                      0
Pt Exp Group Footnote                               3151
TE Group Measure Count                                 0
Count of Facility TE Measures                          0
TE Group Footnote                                   4486
dtype: int64

In [60]:
#dropping all missing values rows
# df_missing=df.dropna(inplace=True)

#data.fillna()
df_missing_values = df.isnull().sum()

df_missing_values

Facility ID                                            0
Facility Name                                          0
Address                                                0
City/Town                                              0
State                                                  0
ZIP Code                                               0
County/Parish                                          0
Telephone Number                                       0
Hospital Type                                          0
Hospital Ownership                                     0
Emergency Services                                     0
Meets criteria for birthing friendly designation    3161
Hospital overall rating                                0
Hospital overall rating footnote                    2854
MORT Group Measure Count                               0
Count of Facility MORT Measures                        0
Count of MORT Measures Better                          0
Count of MORT Measures No Different                    0
Count of MORT Measures Worse                           0
MORT Group Footnote                                 3639
Safety Group Measure Count                             0
Count of Facility Safety Measures                      0
Count of Safety Measures Better                        0
Count of Safety Measures No Different                  0
Count of Safety Measures Worse                         0
Safety Group Footnote                               3347
READM Group Measure Count                              0
Count of Facility READM Measures                       0
Count of READM Measures Better                         0
Count of READM Measures No Different                   0
Count of READM Measures Worse                          0
READM Group Footnote                                4266
Pt Exp Group Measure Count                             0
Count of Facility Pt Exp Measures                      0
Pt Exp Group Footnote                               3151
TE Group Measure Count                                 0
Count of Facility TE Measures                          0
TE Group Footnote                                   4486
dtype: int64

In [61]:
#dealing with duplicatesrows
duplicates_df = df.duplicated().sum()
df.head()

,Facility ID,Facility Name,Address,City/Town,State,ZIP Code,County/Parish,Telephone Number,Hospital Type,Hospital Ownership,...,Count of READM Measures Better,Count of READM Measures No Different,Count of READM Measures Worse,READM Group Footnote,Pt Exp Group Measure Count,Count of Facility Pt Exp Measures,Pt Exp Group Footnote,TE Group Measure Count,Count of Facility TE Measures,TE Group Footnote
0,10001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,Acute Care Hospitals,Government - Hospital District or Authority,...,0,11,0,NaN,8,8,NaN,12,11,NaN
1,10005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,(256) 593-8310,Acute Care Hospitals,Government - Hospital District or Authority,...,0,8,1,NaN,8,8,NaN,12,12,NaN
2,10006,NORTH ALABAMA MEDICAL CENTER,1701 VETERANS DRIVE,FLORENCE,AL,35630,LAUDERDALE,(256) 768-8400,Acute Care Hospitals,Proprietary,...,0,8,1,NaN,8,8,NaN,12,10,NaN
3,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,(334) 493-3541,Acute Care Hospitals,Voluntary non-profit - Private,...,0,7,0,NaN,8,8,NaN,12,7,NaN
4,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,(334) 335-3374,Acute Care Hospitals,Proprietary,...,0,2,0,NaN,8,Not Available,5.0,12,6,NaN

In [62]:
#deleting all duplicated rows
# data[data.duplicated()]

df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [63]:
#type casting 
#chaning data types
df.dtypes
df.head()

,Facility ID,Facility Name,Address,City/Town,State,ZIP Code,County/Parish,Telephone Number,Hospital Type,Hospital Ownership,...,Count of READM Measures Better,Count of READM Measures No Different,Count of READM Measures Worse,READM Group Footnote,Pt Exp Group Measure Count,Count of Facility Pt Exp Measures,Pt Exp Group Footnote,TE Group Measure Count,Count of Facility TE Measures,TE Group Footnote
0,10001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,Acute Care Hospitals,Government - Hospital District or Authority,...,0,11,0,NaN,8,8,NaN,12,11,NaN
1,10005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,(256) 593-8310,Acute Care Hospitals,Government - Hospital District or Authority,...,0,8,1,NaN,8,8,NaN,12,12,NaN
2,10006,NORTH ALABAMA MEDICAL CENTER,1701 VETERANS DRIVE,FLORENCE,AL,35630,LAUDERDALE,(256) 768-8400,Acute Care Hospitals,Proprietary,...,0,8,1,NaN,8,8,NaN,12,10,NaN
3,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,(334) 493-3541,Acute Care Hospitals,Voluntary non-profit - Private,...,0,7,0,NaN,8,8,NaN,12,7,NaN
4,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,(334) 335-3374,Acute Care Hospitals,Proprietary,...,0,2,0,NaN,8,Not Available,5.0,12,6,NaN

In [66]:
df['Facility ID'] = df['Facility ID'].astype('Int64')

ValueError: invalid literal for int() with base 10: '01014F'

In [67]:
df.dtypes

Facility ID                                          object
Facility Name                                        object
Address                                              object
City/Town                                            object
State                                                object
ZIP Code                                              int64
County/Parish                                        object
Telephone Number                                     object
Hospital Type                                        object
Hospital Ownership                                   object
Emergency Services                                   object
Meets criteria for birthing friendly designation     object
Hospital overall rating                              object
Hospital overall rating footnote                     object
MORT Group Measure Count                             object
Count of Facility MORT Measures                      object
Count of MORT Measures Better                        object
Count of MORT Measures No Different                  object
Count of MORT Measures Worse                         object
MORT Group Footnote                                 float64
Safety Group Measure Count                           object
Count of Facility Safety Measures                    object
Count of Safety Measures Better                      object
Count of Safety Measures No Different                object
Count of Safety Measures Worse                       object
Safety Group Footnote                                object
READM Group Measure Count                            object
Count of Facility READM Measures                     object
Count of READM Measures Better                       object
Count of READM Measures No Different                 object
Count of READM Measures Worse                        object
READM Group Footnote                                float64
Pt Exp Group Measure Count                           object
Count of Facility Pt Exp Measures                    object
Pt Exp Group Footnote                               float64
TE Group Measure Count                               object
Count of Facility TE Measures                        object
TE Group Footnote                                   float64
dtype: object

In [69]:
df.to_csv('cleaned_provider_infos.csv', index=False)